#pragma kernel CSMain

Texture2D<float4> mask;
RWTexture2D<float4> result;				//Result baked texture

SamplerState _LinearClamp;

[numthreads(8,8,1)]
void CSMain (uint2 id : SV_DispatchThreadID)
{
	float w, h;
    result.GetDimensions(w, h);
    float2 uv = float2(id.x/(w - 1), id.y/(h - 1));

	//Calculate mask color texel
	float4 masked = mask.SampleLevel(_LinearClamp, uv, 0);

	//Peek resampled mask texture
	float4 resultPixel = masked;									
    result[id] = resultPixel;
}
